#!/usr/bin/env python3
"""Write docs-site/hugo-local-version.yaml: a local-only Hugo config overlay
that builds a single docs version, for a quicker `make serve-docs VERSION=…`.

`make serve-docs` renders every version tree under docs-site/content/<section>/
(kagent/0.x and kagent/1.x). When you only need one version, the other one is
wasted time. This overlay adds an `ignoreFiles` pattern for every other version
directory, so Hugo never reads those trees. Unversioned sections, such as kmcp,
always build.

Nothing is maintained by hand. The versions come from `params.versions` in
docs-site/hugo.yaml; --version takes a linkVersion (the version tree's directory
name, such as `0.x` or `1.x`), or `latest` for the entry marked `latest: true`
(the first entry if none is). The overlay is gitignored and only ever passed by
the Makefile's `serve-docs` target, never by a production build.

Links into the versions that are left out (the version dropdown, cross-version
links) do not resolve locally.
"""

import argparse
import re
import sys
from pathlib import Path

DOCS_SITE = Path(__file__).resolve().parent.parent / "docs-site"
CONFIG = DOCS_SITE / "hugo.yaml"
CONTENT = DOCS_SITE / "content"
OUT = DOCS_SITE / "hugo-local-version.yaml"

# Directory names that are version trees. Anything else under a section (an
# _index.md, an unversioned topic directory) is never skipped.
VERSION_DIR = re.compile(r"^(?:\d+\.x|\d+\.\d+\.(?:x|\d+)|latest|main)$")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", required=True, help="the linkVersion to build, or `latest`")
    args = parser.parse_args()

    try:
        import yaml
    except ImportError:
        sys.exit("ERROR: VERSION needs PyYAML to read hugo.yaml. Run `pip3 install pyyaml`.")

    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}
    entries = (config.get("params") or {}).get("versions") or []
    listed = [str(e.get("linkVersion") or e.get("version")) for e in entries]
    if args.version in listed:
        keep = args.version
    elif args.version == "latest" and entries:
        latest = next((e for e in entries if e.get("latest")), entries[0])
        keep = str(latest.get("linkVersion") or latest.get("version"))
    else:
        sys.exit(
            f"ERROR: VERSION={args.version} is not a linkVersion in docs-site/hugo.yaml "
            f"(have: latest, {', '.join(listed)})"
        )

    sections = sorted({s for e in entries for s in e.get("sections") or []})
    patterns, skipped = [], []
    for section in sections:
        section_dir = CONTENT / section
        if not section_dir.is_dir():
            continue
        for version_dir in sorted(p for p in section_dir.iterdir() if p.is_dir()):
            name = version_dir.name
            if VERSION_DIR.match(name) and name != keep:
                patterns.append(f"(^|/)content/{re.escape(section)}/{re.escape(name)}/")
                skipped.append(f"{section}/{name}")

    text = (
        "# GENERATED by scripts/local-version-config.py for `make serve-docs VERSION=…`.\n"
        "# Gitignored; never pass it to a production build.\n"
        "ignoreFiles:\n"
        + "".join(f"  - '{p}'\n" for p in patterns)
        # Pages outside the kept version `ref` pages in the skipped versions.
        # Missing refs fail the build; warn instead.
        + "refLinksErrorLevel: warning\n"
    )
    OUT.write_text(text, encoding="utf-8")

    print(f"Building version {keep} only; skipping {', '.join(skipped) or 'nothing'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
